package cz.leris.playgames.server.generaldao;

import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 * Created by jirka on 24.6.17.
 */
public interface StatementFactory {
    PreparedStatement prepareStatement(String sql) throws SQLException;
    PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException;
	<T> T execute(TransactionTask<T> t) throws Exception;
}
